#Indicamos la version del archivo docker compose
version: "3"
#Declaramos los servicios que se van iniciar e incluir en el docker
services:
  #Indicamos un nombre para el servicio
  apis:
    #Indicar donde se encuentra el dockerfile del servicio
    build: ./BackendConsultas
    depends_on:
      - mongo
    #Establecemos variables de entorno
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/bibliotecabot
      - APPLICATION_NAME:BackendConsultas
    #Se establece el puerto interno y externo por el cual saldra nuestro servicio
    ports:
      - "3000:3000"

  mongo:
    image: mongo
